# Generated by Django 4.0.1 on 2022-02-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
