# Generated by Django 4.0.1 on 2022-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_entry_solve_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='username',
            field=models.TextField(max_length=20),
        ),
    ]
