# Generated by Django 4.0.1 on 2022-02-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_alter_entry_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
