# Generated by Django 4.0.1 on 2022-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_alter_entry_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='seconds',
        ),
        migrations.AddField(
            model_name='entry',
            name='solve_time',
            field=models.IntegerField(default=0),
        ),
    ]
