# Generated by Django 4.0.1 on 2022-03-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_remove_entry_hours_remove_entry_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='username',
            field=models.TextField(),
        ),
    ]
