# Generated by Django 4.0.1 on 2022-03-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_alter_entry_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='solve_time',
        ),
        migrations.AddField(
            model_name='entry',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
