# Generated by Django 4.0.1 on 2022-04-19 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_entry_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 4, 19, 3, 32, 18, 483158, tzinfo=utc)),
        ),
    ]
