# Generated by Django 4.0.1 on 2022-04-19 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_alter_entry_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name=datetime.datetime(2022, 4, 19, 3, 38, 23, 579642, tzinfo=utc)),
        ),
    ]
