# Generated by Django 4.0.1 on 2022-04-22 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0015_alter_entry_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
